export const FETCH_QUESTIONS = 'Trivia/FETCH_QUESTIONS';
export const FETCH_QUESTIONS_SUCCESS = 'Trivia/FETCH_QUESTIONS_SUCCESS';
export const FETCH_QUESTIONS_FAIL = 'Trivia/FETCH_QUESTIONS_FAIL';
export const ANSWER_QUESTION = 'Trivia/ANSWER_QUESTION';
export const RESET_QUESTIONS = 'Trivia/RESET_QUESTIONS';
